Fix sidebar placement
WildCodeSchool/2022-03-php-orleans-project-aoyos pull request #135
Opened 2022-06-11 08:24 UTC by MGliem

2022-06-11 12:52 UTC, VanTej approved these changes

2022-06-12 21:13 UTC, sblondeau requested changes

2022-06-12 21:13 UTC, sblondeau commented on assets/adminSidebar.js
> +if (window.innerWidth >= breakPointWidth) {
https://getbootstrap.com/docs/5.1/components/offcanvas/#backdrop
c'est pas juste une classe .show sur laquelle il faut jouer ?

2022-06-12 21:22 UTC, MGliem commented on assets/adminSidebar.js
> +if (window.innerWidth >= breakPointWidth) {
Je ne pense pas sinon elle garde un comportement 'position: fixed' alors qu'en ecran desktop on préfère avoir un comportement sticky pour qu'elle ne se mette pas au dessus du reste du contenu.

2022-06-13 07:48 UTC, Chloebert submitted a review, later dismissed

2022-06-13 11:57 UTC, Ysedda approved these changes

2022-06-13 19:23 UTC, VanTej approved these changes

2022-06-14 09:12 UTC, merged