S02 us50 admin edit services
WildCodeSchool/2022-03-php-orleans-project-aoyos pull request #137
Opened 2022-06-11 11:34 UTC by VanTej

2022-06-11 20:47 UTC, MGliem approved these changes

2022-06-11 20:47 UTC, MGliem commented on src/Controller/AdminArticleController.php
> +            $date = new DateTime();
Ca fonctionne mais on peut aussi faire une requete SQL maison qui fait un NOW() dans le champ created_at.

2022-06-12 21:18 UTC, sblondeau requested changes

2022-06-12 21:18 UTC, sblondeau commented on src/Controller/AdminArticleController.php
> +            $date = new DateTime();
le mieux est encore de mettre ça dans le construct d'Article
```
public function __construct() 
{
    $this->createdAt = new DateTime();
}

```
Attention, si vous mettez un champ de type datetime en BDD, doctrine attend un type DateTime PHP pour la propriété, c'est tout à fait normal. 
C'est au moment de l'affichage (donc dans Twig) qu'il faut faire un format.

2022-06-12 21:18 UTC, sblondeau commented on migrations/Version20220611111633.php
> +        $this->addSql('ALTER TABLE article CHANGE created_at created_at VARCHAR(10) NOT NULL');
non il faut garder un DATETIME

2022-06-12 21:18 UTC, sblondeau commented on src/DataFixtures/ArticleFixtures.php
> +            $article->setCreatedAt($date->format('d-m-Y'));
là on veut un objet Datetime

2022-06-12 21:18 UTC, sblondeau commented on src/Entity/Article.php
> +    public function getCreatedAt(): ?string
datetime

2022-06-12 21:18 UTC, sblondeau commented on src/Entity/Article.php
> +    #[Assert\Length(
Assert\Datetime

2022-06-13 15:19 UTC, sblondeau approved these changes

2022-06-13 15:19 UTC, merged