S02 us06 home presentation
WildCodeSchool/2022-03-php-orleans-project-aoyos pull request #139
Opened 2022-06-11 16:21 UTC by Ysedda

2022-06-11 20:58 UTC, MGliem requested changes
Un peu bizarre d'appeler les images "test-bleu". Appel les pluôt "title_underline_blue" par exemple

2022-06-11 20:58 UTC, MGliem commented on assets/styles/home.scss
> +.who {
Ca va nous servir sur pas mal de titre, donne lui un nom du style "title-underline" et met le dans le app.scss

2022-06-11 20:58 UTC, MGliem commented on assets/styles/home.scss
> +    width: 50px;
En variable au début du fichier

2022-06-11 20:58 UTC, MGliem commented on templates/components/_home_presentation.html.twig
> +	<div class="d-flex flex-wrap aoyosPresentation justify-content-center flex-column col-11 align-items-center mt-5 pb-4 mx-auto">
kebab-case pour le css et pas camelCase :) (aoyosPresentation)

2022-06-11 20:58 UTC, MGliem commented on templates/components/_home_presentation.html.twig
> +			<div class="d-md-flex aoyosLogoDiv d-none justify-content-center align-items-center h-100 w-100 py-4">
idem kebab-case

2022-06-11 20:58 UTC, MGliem commented on templates/components/_home_presentation.html.twig
> +				<div class="aoyosPresentationImage h-100 col-8 mb-3"></div>
idem kebab-case

2022-06-11 20:58 UTC, MGliem commented on templates/components/_home_presentation.html.twig
> +		<a href="" class="btn btn-outline-primary showTeam text-dark">Voir l'équipe</a>
idem kebab-case

2022-06-12 13:24 UTC, Chloebert requested changes

2022-06-12 13:24 UTC, Chloebert commented on templates/components/_home_presentation.html.twig
> +		<a href="" class="btn btn-outline-primary showTeam text-dark">Voir l'équipe</a>
Je vois toujours le showTeam :(

2022-06-12 19:53 UTC, Chloebert approved these changes

2022-06-12 21:28 UTC, sblondeau approved these changes

2022-06-12 21:28 UTC, sblondeau commented on templates/components/_home_presentation.html.twig
> +			<img src="{{ asset('build/images/title_underline_blue.png') }}" class="title-underline" alt="">
tu utilises que la blue finalement ? les autres te servent pas ?
dans l'idéal, je pense que vous pourriez ne gérer qu'une seule image et modifier la couleurs en CSS via un filter:hue() 
C'est pas une obligation mais c'est une approche plus intéressante car vous n'êtes pas limité en nombre de coloris du coup
et le top du top serait d'avoir ça en SVG mais là on va dire que je pinaille :D

2022-06-12 21:28 UTC, merged