structure form delete et ajout du bouton supprimer sur index
WildCodeSchool/2022-03-php-orleans-project-aoyos pull request #145
Opened 2022-06-12 12:06 UTC by Chloebert

2022-06-12 14:41 UTC, VanTej approved these changes

2022-06-12 21:37 UTC, sblondeau requested changes

2022-06-12 21:37 UTC, sblondeau commented on templates/admin_team_member/_delete_form.html.twig
> +<form method="post" action="{{ path('admin_team_member_delete', {'id': team_member.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer {{ team_member.name }} ?');">
juste "de vouloir supprimer le membre?", n'affiche pas le nom ici car il peut-etre très long

2022-06-13 08:53 UTC, VanTej approved these changes

2022-06-13 09:22 UTC, sblondeau approved these changes

2022-06-13 09:22 UTC, merged