S02 us30 login admin
WildCodeSchool/2022-03-php-orleans-project-aoyos pull request #201
Opened 2022-06-15 14:21 UTC by Chloebert

2022-06-15 14:43 UTC, VanTej commented on config/packages/security.yaml
> +            ROLE_ADMIN: ROLE_ADMIN
ROLE_ADMIN: ROLE_USER

2022-06-15 15:00 UTC, MGliem approved these changes

2022-06-15 15:28 UTC, sblondeau requested changes

2022-06-15 15:28 UTC, sblondeau commented on src/Controller/LoginController.php
> +            'controller_name' => 'LoginController',
controller_name c'est en trop (c'est un bout de l'exemple que te génère le make:controller)

2022-06-15 15:28 UTC, sblondeau commented on templates/login/index.html.twig
> +				<input type="hidden" name="_target_path" value={% if is_granted('ROLE_ADMIN') %} "/admin" {% else %} "/" {% endif %}/>
comme discuté, à modif

2022-06-16 08:15 UTC, sblondeau approved these changes

2022-06-16 08:15 UTC, merged