changed polices and add bootstrap theme on forms by defaults in twig …
WildCodeSchool/2022-03-php-orleans-project-aoyos pull request #3
Opened 2022-06-03 14:42 UTC by MGliem

…config

2022-06-03 14:44 UTC, Chloebert approved these changes

2022-06-04 06:47 UTC, sblondeau requested changes

2022-06-04 06:47 UTC, sblondeau commented on assets/styles/variables.scss
> +$lineHeight: 1.5px;
non c'est juste 1.5 (c'est à dire que tu  multiplies par 1.5 la taille de la police), et pas en px

2022-06-04 06:47 UTC, sblondeau commented on assets/styles/variables.scss
> +$lineHeight: 1.5px;
https://developer.mozilla.org/fr/docs/Web/CSS/line-height

2022-06-07 14:32 UTC, Chloebert approved these changes

2022-06-08 09:38 UTC, Ysedda approved these changes

2022-06-08 09:44 UTC, sblondeau approved these changes

2022-06-08 09:44 UTC, merged