S04 us74 dj gps coords
WildCodeSchool/2022-03-php-orleans-project-aoyos pull request #378
Opened 2022-06-27 14:49 UTC by Ysedda

2022-06-28 06:58 UTC, Chloebert submitted a review, later dismissed

2022-06-28 09:29 UTC, sblondeau requested changes
prendre en compte le cas où l'API renvoie pas de résultat ?

2022-06-28 09:29 UTC, sblondeau commented on src/Entity/Artist.php
> +    private Coordinate $coordinates;
pas besoin d'une table à mon avis, plutot 2 champs latitude et longitude

2022-06-28 15:21 UTC, MGliem approved these changes

2022-06-28 21:21 UTC, sblondeau requested changes

2022-06-28 21:21 UTC, sblondeau commented on src/Service/DistanceCalculator.php
> +            throw new Exception('Une erreur est survenue lors de la récupération de l\'adresse');
pas sûr de te suivre, tu throw une Exception mais dans le try tu catch un TransportException

2022-06-28 21:21 UTC, sblondeau commented on src/Controller/DjController.php
> +    private function addCoordinates(DistanceCalculator $distanceCalculator, Artist $artist): void
un peu bizarre de déporter ça dans un méthode privée, on y gagne pas vraiment en lisibilité

2022-06-29 07:34 UTC, sblondeau approved these changes

2022-07-04 07:11 UTC, MGliem approved these changes

2022-07-04 07:18 UTC, merged