S04 us26 dj s events
WildCodeSchool/2022-03-php-orleans-project-aoyos pull request #381
Opened 2022-06-27 16:24 UTC by VanTej

2022-06-28 08:47 UTC, Ysedda approved these changes

2022-06-28 11:52 UTC, sblondeau requested changes

2022-06-28 11:52 UTC, sblondeau commented on src/Controller/DjDashboardController.php
> +    #[Route('/mes-evenements-{filtre}', name: 'my_events', requirements: ['filtre' => 'passes|a-venir'])]
/mes-evenements/{filter}

2022-06-28 11:52 UTC, sblondeau commented on src/Controller/DjDashboardController.php
> +        }
ça c'est à faire dans la requete perso

2022-06-28 11:52 UTC, sblondeau commented on src/Controller/DjDashboardController.php
> +        }
et passes/à venir c'est plus à mettre dans 2 constantes (PAST_EVENTS = 'passes', FUTURE_EVENTS = 'a-venir')

2022-06-28 11:52 UTC, sblondeau commented on src/Repository/ReservationRepository.php
> +        return $this->createQueryBuilder('r')
et donc là tu testes si condition est égale à une des 2 constantes)

2022-06-28 11:52 UTC, sblondeau commented on templates/dj_dashboard/my_events.html.twig
> +				{% if filtre == 'passes' %} passés
tu devrais faire réléféence aux constantes ici

2022-06-28 11:52 UTC, sblondeau commented on src/Controller/DjDashboardController.php
> +            'filtre' => $filtre
filter

2022-06-28 13:58 UTC, MGliem approved these changes

2022-06-28 13:59 UTC, Chloebert submitted a review, later dismissed

2022-06-28 14:53 UTC, sblondeau requested changes

2022-07-04 11:00 UTC, Ysedda approved these changes

2022-07-04 11:36 UTC, sblondeau submitted a review, later dismissed

2022-07-04 13:42 UTC, merged