S03 us82 admin reservation filtre status
WildCodeSchool/2022-03-php-orleans-project-aoyos pull request #416
Opened 2022-07-04 14:19 UTC by MGliem

2022-07-04 14:31 UTC, VanTej approved these changes

2022-07-05 09:37 UTC, VanTej submitted a review, later dismissed

2022-07-05 09:45 UTC, sblondeau requested changes

2022-07-05 09:45 UTC, sblondeau commented on src/Form/SearchAdminReservationType.php
> +                    'onchange' => 'document.forms["search_admin_reservation"].submit()'
j'aurais plutot mis ça dans un fichier séparé, ou au pire coté twig, ça me fait bizarre d'avoir du JS dans le fichier form :/
sinon,  un this.form.submit() fonctionne pas  ?

2022-07-05 10:04 UTC, Ysedda approved these changes

2022-07-05 10:18 UTC, sblondeau approved these changes

2022-07-05 13:29 UTC, merged