searchbar on dj offers
WildCodeSchool/2022-03-php-orleans-project-aoyos pull request #433
Opened 2022-07-05 14:17 UTC by VanTej

2022-07-05 15:12 UTC, Ysedda submitted a review, later dismissed

2022-07-05 15:35 UTC, sblondeau requested changes

2022-07-05 15:35 UTC, sblondeau commented on src/Form/SearchDjReservationsType.php
> +            ->add('search', SearchType::class, [
les styles musicaux sont dans une table ? c'est une liste finie non ? (contrairement à un nom d'event par ex). Donc ça ne serait pas plus logique de faire un EntityType ici plutot , et donc pas besoin d'un requete perso avec un LIKE

2022-07-06 10:19 UTC, Ysedda submitted a review, later dismissed

2022-07-06 10:34 UTC, sblondeau approved these changes

2022-07-06 11:36 UTC, MGliem approved these changes

2022-07-06 11:41 UTC, merged