fix - dj show reservation null fields
WildCodeSchool/2022-03-php-orleans-project-aoyos pull request #491
Opened 2022-07-07 15:02 UTC by Chloebert

2022-07-07 15:06 UTC, MGliem submitted a review, later dismissed

2022-07-07 22:26 UTC, sblondeau requested changes

2022-07-07 22:26 UTC, sblondeau commented on templates/dj_dashboard/reservation/show.html.twig
> +								{% if not loop.last %},
regarde le join en Twig  https://twig.symfony.com/doc/2.x/filters/join.html
ça devrait t'éviter le bidouillage avec le not loop. last ;-)

2022-07-08 07:49 UTC, Ysedda approved these changes

2022-07-08 08:03 UTC, merged