S01US41 admin partners show
WildCodeSchool/2022-03-php-orleans-project-aoyos pull request #63
Opened 2022-06-08 15:02 UTC by Ysedda

2022-06-08 15:07 UTC, MGliem requested changes

2022-06-08 15:07 UTC, MGliem commented on templates/admin_partner/index.html.twig
> +                <th>Image</th>
il te manque des TH, tu as 4 colonnes avec les boutons et pas que 2

2022-06-08 17:56 UTC, MGliem submitted a review, later dismissed

2022-06-09 09:09 UTC, sblondeau requested changes

2022-06-09 09:09 UTC, sblondeau commented on templates/admin/partner/index.html.twig
> +                <td class="align-middle">{{ partner.image }}</td>
soit tu ne mets pas l'image, soit tu la mets dans une balise img

2022-06-09 09:18 UTC, Chloebert approved these changes

2022-06-09 09:35 UTC, sblondeau approved these changes

2022-06-09 09:46 UTC, merged