S01 us49 admin list services
WildCodeSchool/2022-03-php-orleans-project-aoyos pull request #65
Opened 2022-06-08 15:21 UTC by VanTej

2022-06-08 19:17 UTC, Chloebert approved these changes

2022-06-09 09:12 UTC, sblondeau requested changes

2022-06-09 09:12 UTC, sblondeau commented on templates/admin_article/index.html.twig
> +						<td colspan="7">no records found</td>
trad, le colspan est passé à 5 non ?

2022-06-09 09:12 UTC, sblondeau commented on templates/admin_article/index.html.twig
> +{% block title %}Article index
tu laisse article index ?

2022-06-09 09:25 UTC, Chloebert approved these changes

2022-06-09 09:50 UTC, sblondeau approved these changes

2022-06-09 14:46 UTC, closed without merging