S01 us44 team member add
WildCodeSchool/2022-03-php-orleans-project-aoyos pull request #84
Opened 2022-06-10 08:58 UTC by Chloebert

2022-06-10 15:11 UTC, MGliem submitted a review, later dismissed

2022-06-10 15:26 UTC, sblondeau requested changes

2022-06-10 15:26 UTC, sblondeau commented on migrations/Version20220610084500.php
> +    public function up(Schema $schema): void
trop de truc dans ta migration ?! meme pas bien sûr que tu devais avoir une migration, toutes ces tables ont déjà été créées non ? tu as du drop ta base et faire un make:migration alors qu'un d:m:m était suffisant

2022-06-10 15:26 UTC, sblondeau commented on src/Entity/TeamMember.php
> +    #[Assert\Length(
c'est une URL? 
Assert\Url
et dans le form => UrlType et non TextType

2022-06-12 11:24 UTC, Chloebert commented on src/Entity/TeamMember.php
> +    #[Assert\Length(
Pour l'instant on est pas sûr de ça, mais je vais le changer en URL au cas où pour être plus cohérent avec le reste des cruds

2022-06-12 14:44 UTC, VanTej approved these changes

2022-06-12 21:04 UTC, sblondeau approved these changes

2022-06-12 21:04 UTC, merged