fix footer
WildCodeSchool/2022-03-php-orleans-project-aoyos pull request #89
Opened 2022-06-10 13:54 UTC by Ysedda

2022-06-10 14:56 UTC, Chloebert submitted a review, later dismissed

2022-06-10 15:02 UTC, sblondeau approved these changes

2022-06-10 15:03 UTC, sblondeau requested changes

2022-06-10 15:03 UTC, sblondeau commented on templates/components/_footer.html.twig
> +	<h3>
pourquoi un h3 ? :p tu peux repartir d'un h1 dans le footer, ou un h2 éventuellement, mais pas un h3 c'est pas logique en terme de hierarchie des titres

2022-06-11 08:31 UTC, MGliem approved these changes

2022-06-12 21:04 UTC, sblondeau approved these changes

2022-06-12 21:04 UTC, merged